export const researchAtlas = {
  eyebrow: 'An Odyssey through the Mind',
  title: 'Mechanisms of Attention and Planning',
  lede: 'How do brains and machines select what matters, then decide how far ahead to think?',
  frame: 'Four projects, one thread: cognition is selective. My work asks how agents allocate attention, adapt planning effort, represent strategic futures, and decide when further computation is worth it.',
  chapters: [
    {
      number: '01',
      slug: 'attention',
      theme: 'Attention',
      subtitle: 'Bidirectional Recurrent Gating',
      question: 'Recurrent gating for visual attention',
      backdrop: '/images/research/attention-architecture.png',
      artifact: '/images/research/attention-tasks.png',
      artifactAlt: 'Bidirectional recurrent gating model architecture and attention-task outputs',
      motif: 'Architecture and task behavior',
      prompt: 'Can recurrent gating explain attention, binding, and task-dependent visual selection?',
      summary: 'This project asks whether attention and binding can emerge from a biologically inspired neural network with bidirectional recurrent gating between feature and attention pathways.',
      takeaways: [
        { label: 'Architecture', text: 'Feature maps and attention maps interact through multiplicative recurrent gates.' },
        { label: 'Tasks', text: 'The model learns object recognition, grouping, orienting, tracking, pop-out, inhibition of return, and top-down search.' },
        { label: 'Behavior', text: 'The same mechanism reproduces signatures from psychophysics and neural modulation.' },
      ],
      finding: 'Bidirectional recurrent gating provides a unified computational account of attention, binding, and task-dependent visual selection.',
      interpretation: 'The model is useful less as an engineering trick than as a bridge between neural architecture, behavioral attention phenomena, and learned visual computation.',
      resources: [
        { href: 'https://www.nature.com/articles/s41467-026-72146-9', label: 'Nature Communications' },
      ],
    },
    {
      number: '02',
      slug: 'uncertainty',
      theme: 'Stochasticity',
      subtitle: 'Triangle of Treasures',
      question: 'Planning under environmental stochasticity',
      backdrop: '/images/research/treasure-task.png',
      artifact: '/images/research/treasure-policy-compression.png',
      artifactAlt: 'Choice, reward, and policy-compression results across reliability, volatility, and controllability conditions',
      motif: 'Task and model results',
      prompt: 'How do people adapt their plans in unpredictable environments?',
      summary: 'Participants navigated a branching tree of treasure chests while the task varied three kinds of stochasticity: unreliable rewards, volatile future states, and imperfect control over actions.',
      takeaways: [
        { label: 'Task', text: 'People planned routes through a branching treasure tree while the environment became less predictable.' },
        { label: 'Analysis', text: 'Computational model comparison separated changes in planning depth from changes in value precision.' },
        { label: 'Result', text: 'Across the three forms of stochasticity, fitted policy-compression parameters declined.' },
      ],
      finding: 'When the environment was less predictable, choices became less sensitive to fine value differences, most clearly through policy compression.',
      interpretation: 'When the world is less predictable, planning becomes more approximate.',
      dynamicFigure: 'stochasticity',
      taskDemo: true,
      resources: [
        { href: 'https://files.osf.io/v1/resources/bh56p_v1/providers/osfstorage/6813cdf8a74db1488d3cbf6a?action=download&direct&version=1', label: 'Preprint' },
        { href: '/files/TreasureHuntPoster.pdf', label: 'Poster' },
      ],
    },
    {
      number: '03',
      slug: 'opponents',
      theme: 'Neural',
      subtitle: 'Four-in-a-Row',
      question: 'Planning against a strategic opponent',
      backdrop: '/images/research/fourinarow-task.png',
      artifact: '/images/research/fourinarow-model-comparison.png',
      artifactAlt: 'Cross-validated comparison of tree-search, myopic, and feature-lesion models in Four-in-a-Row',
      portrait: '/images/research/rhesus-macaque.jpg',
      portraitAlt: 'Rhesus macaque',
      motif: 'Four-in-a-Row and behavioral model',
      prompt: 'How does the brain plan in complex strategy games?',
      summary: 'A rhesus macaque played Four-in-a-Row against a computer opponent in a 4 × 9 game with roughly 10¹⁶ nonterminal states. The project links choices, gaze, and simultaneous recordings from DMPFC, DLPFC, and caudate.',
      takeaways: [
        { label: 'Task', text: 'A monkey learned a large strategic game against an opponent.' },
        { label: 'Search', text: 'Held-out choices were best predicted by feature-based tree search, not myopic alternatives.' },
        { label: 'Neurons', text: 'Neural activity tracked tree-search value beyond a matched myopic baseline.' },
      ],
      finding: 'Preliminary one-animal evidence: the behavioral and neural data are most consistent with deeper-than-myopic tree search.',
      interpretation: 'This is preliminary one-animal evidence, but it shows how systems neuroscience can study planning in a genuinely large state space.',
      dynamicFigure: 'monkey',
      resources: [
        { href: '/files/NeuralPoster.pdf', label: 'Poster' },
      ],
    },
    {
      number: '04',
      slug: 'metacontrol',
      theme: 'Metacontrol',
      subtitle: 'Metaplanning in Chess',
      question: 'Deciding when to stop planning',
      backdrop: '/images/research/chess-metacontroller.png',
      artifact: '/images/research/chess-metacontroller-frontier.png',
      artifactAlt: 'Performance of a learned chess metacontroller compared with stopping baselines',
      motif: 'Learned halt-or-continue control',
      prompt: 'Can we learn when to think?',
      summary: 'Chess makes metaplanning measurable: people spend different amounts of time across board states, and a model can learn whether to halt or continue from the structure of an evolving search tree.',
      takeaways: [
        { label: 'Metacontrol', text: 'Planning has both benefits and costs, so stopping is itself a decision.' },
        { label: 'Behavior', text: 'Chess players spend longer when there is more to consider, including more legal moves and captures.' },
        { label: 'Network', text: 'A graph neural network learned a halt-or-continue policy from partial search trees.' },
      ],
      finding: 'A learned metacontroller can regulate search from the tree itself rather than a fixed compute budget; it remains a normative benchmark, not yet a fitted model of human response time.',
      interpretation: 'The human and model results remain separate for now: this is a normative benchmark, not yet a fitted account of human response time.',
      dynamicFigure: 'chess',
      resources: [],
    },
  ],
}
