export const researchAtlas = {
  eyebrow: 'An Odyssey through the Mind',
  title: 'Mechanisms of Adaptive Planning',
  lede: 'How do people, animals, and machines decide when thinking ahead is worth the effort?',
  frame: 'Three projects, one question: planning is powerful, but it is also costly. My work asks how agents adapt that effort when the world is uncertain, strategic, or computationally demanding.',
  chapters: [
    {
      number: '01',
      slug: 'uncertainty',
      theme: 'Stochasticity',
      subtitle: 'Triangle of Treasures',
      question: 'Planning under environmental stochasticity',
      backdrop: '/images/research/treasure-task.png',
      artifact: '/images/research/treasure-policy-compression.png',
      artifactAlt: 'Choice, reward, and policy-compression results across reliability, volatility, and controllability conditions',
      motif: 'Task and model results',
      prompt: 'How do people adapt their plans in unpredictable environments?',
      summary: 'Participants navigated a branching tree of treasure chests while the task varied three kinds of stochasticity: unreliable rewards, volatile future states, and imperfect control over actions.',
      takeaways: [
        { label: 'Effort', text: 'First-choice response times fell as stochasticity increased.' },
        { label: 'Model', text: 'The best account combined depth-limited representations, determinizing value functions, and policy compression.' },
        { label: 'Interpretation', text: 'People did not merely stop planning deeper; they became less sensitive to fine value differences when precision mattered less.' },
      ],
      finding: 'Stochasticity lowers planning effort, expressed most clearly as policy compression.',
      interpretation: 'When the world is less predictable, planning becomes more approximate.',
      resources: [
        { href: 'https://files.osf.io/v1/resources/bh56p_v1/providers/osfstorage/6813cdf8a74db1488d3cbf6a?action=download&direct&version=1', label: 'Preprint' },
        { href: '/files/TreasureHuntPoster.pdf', label: 'Poster' },
      ],
    },
    {
      number: '02',
      slug: 'opponents',
      theme: 'Neural',
      subtitle: 'Four-in-a-Row',
      question: 'Planning against a strategic opponent',
      backdrop: '/images/research/fourinarow-task.png',
      artifact: '/images/research/fourinarow-model-comparison.png',
      artifactAlt: 'Cross-validated comparison of tree-search, myopic, and feature-lesion models in Four-in-a-Row',
      portrait: '/images/research/rhesus-macaque.jpg',
      portraitAlt: 'Rhesus macaque',
      motif: 'Four-in-a-Row and behavioral model',
      prompt: 'How does the brain plan in complex strategy games?',
      summary: 'A rhesus macaque played Four-in-a-Row against a computer opponent in a 4 × 9 game with roughly 10¹⁶ nonterminal states. The project links choices, gaze, and simultaneous recordings from DMPFC, DLPFC, and caudate.',
      takeaways: [
        { label: 'Task', text: 'A monkey learned a large strategic game against an opponent.' },
        { label: 'Search', text: 'Held-out choices were best predicted by feature-based tree search, not myopic alternatives.' },
        { label: 'Neurons', text: 'Neural activity tracked tree-search value beyond a matched myopic baseline.' },
      ],
      finding: 'The behavioral and neural data are most consistent with deeper-than-myopic tree search.',
      interpretation: 'This is preliminary one-animal evidence, but it shows how systems neuroscience can study planning in a genuinely large state space.',
      resources: [
        { href: '/files/NeuralPoster.pdf', label: 'Poster' },
      ],
    },
    {
      number: '03',
      slug: 'metacontrol',
      theme: 'Metacontrol',
      subtitle: 'Metaplanning in Chess',
      question: 'Deciding when to stop planning',
      backdrop: '/images/research/chess-metacontroller.png',
      artifact: '/images/research/chess-metacontroller-frontier.png',
      artifactAlt: 'Performance of a learned chess metacontroller compared with stopping baselines',
      motif: 'Learned halt-or-continue control',
      prompt: 'Can we learn when to think?',
      summary: 'Chess makes metaplanning measurable: people spend different amounts of time across board states, and a model can learn whether to halt or continue from the structure of an evolving search tree.',
      takeaways: [
        { label: 'Metacontrol', text: 'Planning has both benefits and costs, so stopping is itself a decision.' },
        { label: 'Behavior', text: 'Chess players spend longer when there is more to consider, including more legal moves and captures.' },
        { label: 'Network', text: 'A graph neural network learned a halt-or-continue policy from partial search trees.' },
      ],
      finding: 'The learned metacontroller can regulate search from the tree itself, rather than from a fixed compute budget.',
      interpretation: 'The human and model results remain separate for now: this is a normative benchmark, not yet a fitted account of human response time.',
      resources: [],
    },
  ],
}
